language: python
python:
  - "3.7"


cache: pip
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install unittest2
  - pip install numpy
  - pip install sympy 


script: python script_for_test/fk_test.py
  