language: python
python:
  - "3.7"

  
cache: pip
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install unittest
  - pip install numpy
  - pip install sympy 


script: 
  -python src/rostest/src/fk_test.py
  -python src/rostest/src/joint_integration_test.py